#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cd src
wclean
cd ..

for d in applications/* ; do   
    echo $d    
    cd $d
    wclean
    cd ../../
done

cd tutorials

for d in ./*/ ; do   
    echo $d    
    cd $d
    wclean
    cd ../
done

#------------------------------------------------------------------------------
