#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory
cd src

for d in ./*/ ; do   
    echo $d    
    cd $d
    if [ -f "Make/files" ]; then
    wmake $1 $2
     if [ $? -ne 0 ]
     then
      echo $d "did not compile"
      exit 1
     fi
    fi
    cd ../
done


#wmake -j
#if [ $? -ne 0 ]
#then
# echo "library did not compile"
# exit 1
#fi
cd ..

for d in applications/*/ ; do   
    echo $d    
    cd $d
    if [ -f "Make/files" ]; then
    wmake $1 $2
    if [ $? -ne 0 ]
    then
     echo $d "did not compile"
     exit 1
    fi
	fi
    cd ../..
done

cd tutorials

for d in ./*/ ; do   
    echo $d    
    cd $d
    if [ -f "Make/files" ]; then
    wmake $1 $2
     if [ $? -ne 0 ]
     then
      echo $d "did not compile"
      exit 1
     fi
    fi
    cd ../
done

cd ../unitTests

for d in ./*/ ; do   
    echo $d    
    cd $d
    if [ -f "Make/files" ]; then
    wmake $1 $2
    if [ $? -ne 0 ]
    then
     echo $d "did not compile"
     exit 1
    fi
    fi
    cd ../
done




#------------------------------------------------------------------------------
