var searchData=
[
  ['h1seminorm_0',['H1Seminorm',['../namespaceITHACAutilities.html#a6716c521e1e1bef4fdf58a79e6f45d57',1,'ITHACAutilities']]],
  ['homogenizet_1',['homogenizeT',['../classmsrProblem.html#a06e947a616760a7d8ffc7cc7671a0498',1,'msrProblem']]],
  ['homogenizeu_2',['homogenizeU',['../classmsrProblem.html#ade3bb06c9fee6df1224bd77f6a3c154a',1,'msrProblem']]],
  ['hyperreducedcompressibleunsteadyns_3',['HyperReducedCompressibleUnSteadyNS',['../classHyperReducedCompressibleUnSteadyNS.html#a11ed4a05e07545f4dfdde36574e8d0f3',1,'HyperReducedCompressibleUnSteadyNS::HyperReducedCompressibleUnSteadyNS()'],['../classHyperReducedCompressibleUnSteadyNS.html#a0289ffc08b0a86f94bbc9ed5797faa1d',1,'HyperReducedCompressibleUnSteadyNS::HyperReducedCompressibleUnSteadyNS(CompressibleUnSteadyRhoPimple &amp;problem)']]],
  ['hyperreducedsys_4',['HyperReducedSys',['../classHyperReducedCompressibleUnSteadyNS.html#a2f219e220d94df18ae72f388f2e6b803',1,'HyperReducedCompressibleUnSteadyNS']]],
  ['hyperreduction_5',['HyperReduction',['../classHyperReduction.html#a7723e4d96d4eb9971f7303fb0c59dd70',1,'HyperReduction::HyperReduction(label n_modes, label n_nodes, Eigen::VectorXi initialSeeds, word problemName, SnapshotsLists &amp;&amp;...snapshotsLists)'],['../classHyperReduction.html#a5f2b646dc1d8dcc067572af9177a90e0',1,'HyperReduction::HyperReduction(label n_modes, label n_nodes, unsigned int vectorial_dim, label n_cells, Eigen::VectorXi initialSeeds, word problemName, Eigen::VectorXd volumes=Eigen::VectorXd::Constant(1, 0.0))'],['../classDEIM__function.html#a7723e4d96d4eb9971f7303fb0c59dd70',1,'DEIM_function::HyperReduction(label n_modes, label n_nodes, Eigen::VectorXi initialSeeds, word problemName, SnapshotsLists &amp;&amp;...snapshotsLists)'],['../classDEIM__function.html#a5f2b646dc1d8dcc067572af9177a90e0',1,'DEIM_function::HyperReduction(label n_modes, label n_nodes, unsigned int vectorial_dim, label n_cells, Eigen::VectorXi initialSeeds, word problemName, Eigen::VectorXd volumes=Eigen::VectorXd::Constant(1, 0.0))'],['../classHyperReduction__function.html#a7723e4d96d4eb9971f7303fb0c59dd70',1,'HyperReduction_function::HyperReduction(label n_modes, label n_nodes, Eigen::VectorXi initialSeeds, word problemName, SnapshotsLists &amp;&amp;...snapshotsLists)'],['../classHyperReduction__function.html#a5f2b646dc1d8dcc067572af9177a90e0',1,'HyperReduction_function::HyperReduction(label n_modes, label n_nodes, unsigned int vectorial_dim, label n_cells, Eigen::VectorXi initialSeeds, word problemName, Eigen::VectorXd volumes=Eigen::VectorXd::Constant(1, 0.0))'],['../classHyperReduction__vectorFunction.html#a7723e4d96d4eb9971f7303fb0c59dd70',1,'HyperReduction_vectorFunction::HyperReduction(label n_modes, label n_nodes, Eigen::VectorXi initialSeeds, word problemName, SnapshotsLists &amp;&amp;...snapshotsLists)'],['../classHyperReduction__vectorFunction.html#a5f2b646dc1d8dcc067572af9177a90e0',1,'HyperReduction_vectorFunction::HyperReduction(label n_modes, label n_nodes, unsigned int vectorial_dim, label n_cells, Eigen::VectorXi initialSeeds, word problemName, Eigen::VectorXd volumes=Eigen::VectorXd::Constant(1, 0.0))'],['../classHyperReduction__vectorScalarFunction.html#a7723e4d96d4eb9971f7303fb0c59dd70',1,'HyperReduction_vectorScalarFunction::HyperReduction(label n_modes, label n_nodes, Eigen::VectorXi initialSeeds, word problemName, SnapshotsLists &amp;&amp;...snapshotsLists)'],['../classHyperReduction__vectorScalarFunction.html#a5f2b646dc1d8dcc067572af9177a90e0',1,'HyperReduction_vectorScalarFunction::HyperReduction(label n_modes, label n_nodes, unsigned int vectorial_dim, label n_cells, Eigen::VectorXi initialSeeds, word problemName, Eigen::VectorXd volumes=Eigen::VectorXd::Constant(1, 0.0))']]]
];
