#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# To test scalar : -test scalar 
# To test vector + scalar : -test vs 
runApplication 24HyperReduction -test vector 
