#----------------------------------*-sh-*--------------------------------------
# ITHACA-FV:
# In real Time Highly Advanced Computational Applications for Finite Volumes
#------------------------------------------------------------------------------
# Copyright (C) 2020 by the ITHACA-FV authors
# SPDX-License-Identifier: (GPL-3.0+)
#------------------------------------------------------------------------------
# File
#     etc/bashrc
#
# -----------------------------------------------------------------------------

ithacaDir="${BASH_SOURCE:-${ZSH_NAME:+$0}}";
[ -n "$ithacaDir" ] && ithacaDir="$(\cd $(dirname $ithacaDir)/.. && \pwd -L)"

export LIB_ITHACA="$ithacaDir"
export LIB_ITHACA_SRC="$ithacaDir/src"
export PYTHONPATH="$PYTHONPATH:${PYTHONPATH:+:}${LIB_ITHACA_SRC}"/python
export PATH="$PATH:${LIB_ITHACA}"/bin
export includepybind1=$(python3 -m pybind11 --includes | awk -F '-I' '{print $2}')
export includepybind2=$(python3 -m pybind11 --includes | awk -F '-I' '{print $3}')
alias ithaca='cd ${LIB_ITHACA:?}'

unset ithacaDir

# ------------------------------------------------------------------------
