#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication decomposePar
# rm -R ITHACAoutput

runParallel pimpleFoam
bash prep_par_run.sh

# # rm -R log.compare_POD
runParallel compare_POD
