#!/bin/bash
#SBATCH -n 4        # Number of cores
#SBATCH -t 0-00:15  # Runtime in D-HH:MM
#SBATCH --job-name=singularity
#SBATCH -p regular1

echo "Starting singularity on host $HOSTNAME"

image = ./singularity/image/ithicafv.sif

module load singularity/3.4.1

srun -n 4 singularity exec ../../../singularity/image/ithicafv.sif icoFoam

#singularity run ./singularity/image/ithicafv.sif ./tutorials/CFD/01POD/./Allrun

echo "Completed singularity on host $HOSTNAME"

