name: compilation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - name: "OpenFOAM 6"
            install: ./.installOF6.sh
            compile: ./.compileOF6.sh
          - name: "OpenFOAM 5"
            install: ./.installOF5.sh
            compile: ./.compileOF5.sh
          - name: "OpenFOAM 1812"
            install: "cd ."
            compile: ./.compileOF1812.sh

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: install OF
      run: ${{ matrix.install}}
    - name: make
      run: ${{ matrix.compile}}
