name: Build Dependencies Docker Images

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: ithacafv/ithacafv-dependencies

jobs:
  build-amd64-deps:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push AMD64 dependencies
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ./dockerfiles/OF2506/amd64-deps
        platforms: linux/amd64
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build-arm64-deps:
    runs-on: ubuntu-24.04-arm
    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push ARM64 dependencies
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ./dockerfiles/OF2506/arm64-deps
        platforms: linux/arm64
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
