name: OF6

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - name: "OpenFOAM 6"
            compile: ./.compileOF6.sh

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: make
      run: ${{ matrix.compile}}
