name: Singularity_from_Docker_Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  singularity-from-docker-image:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: eWaterCycle/setup-singularity@v7
        with:
           singularity-version: 3.8.3
           
      - name: Allocating the build directory
        run: |
          mkdir `pwd`/mycontainter
          export SINGULARITY_TMPDIR=`pwd`/mycontainter
          export SINGULARITY_CACHEDIR=`pwd`/mycontainter
          export SINGULARITY_BIND=`pwd`/mycontainter
          source /etc/bashrc
        
      - name: Singularity build
        run: singularity build singularity_image.sif docker://mehtapavan/ithacafv-manifest:5
        
      - name: copying necessary files
        run: |
          mv `pwd`/mycontainter/singularity_image.sif `pwd`/tutorials/CFD/01POD/
          mv `pwd`/singularity/Of.sh `pwd`/tutorials/CFD/01POD/
          cd `pwd`/tutorials/CFD/01POD/
        
      - name: Singulairty in batch mode
        run: |
          cd `pwd`/tutorials/CFD/01POD/
          singularity exec singularity_image.sif /bin/bash Of.sh
        
        
      
      
