name: Singularity_from_Docker_Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  singularity-from-docker-image:
    runs-on: ubuntu-latest
    steps:
    
 
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: eWaterCycle/setup-singularity@v7
        with:
           singularity-version: 3.8.3
        
      - name: Singularity build
        run: singularity build singularity_image.sif docker://mehtapavan/ithacafv-manifest:5
        
      - name: copying necessary files
        run: /bin/bash -c "mv singularity_image.sif `pwd`/tutorials/CFD/01POD/ && \ 
          cp `pwd`/singularity/Of.sh `pwd`/tutorials/CFD/01POD/ && \
          cd `pwd`/tutorials/CFD/01POD/"
        
      - name: Run singulairty in batch mode
        run: singularity exec singularity_image.sif /bin/bash Of.sh
        
        
      
      
