name: Singularity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  singularity-from-docker-image:
    runs-on: singularityware/singularity:latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Singularity build
        uses: singularity build singularity_image.sif docker://mehtapavan/ithacafv-manifest:5
        
      - name: moving
        uses: mv singularity_image.sif /tutorials/CFD/01POD/
        
      - name: copying
        uses: cp singularity/Of.sh /tutorials/CFD/01POD/
        
      - name: Run singulairty in batch mode
        uses: singularity exec singularity_image.sif /bin/bash Of.sh
        
        
      
      
