name: Singularity

on:
  push:
    branches: [ master ]

jobs:
  singularity-from-docker-image:
    runs-on: tacc/singularity_test1
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Singularity build
        run: singularity build singularity_image.sif docker://mehtapavan/ithacafv-manifest:5
        
      - name: copying necessary files
        run: | 
          - /bin/bash 
          - -c 
          - mv singularity_image.sif /tutorials/CFD/01POD/ 
          - cp singularity/Of.sh tutorials/CFD/01POD/
          - cd /tutorials/CFD/01POD/
        
      - name: Run singulairty in batch mode
        run: singularity exec singularity_image.sif /bin/bash Of.sh
        
        
      
      
